export type TimezoneGroup = {
  label: string;
  zones: { value: string; label: string }[];
};

export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  {
    label: "UTC",
    zones: [{ value: "UTC", label: "UTC — Coordinated Universal Time" }],
  },
  {
    label: "Americas",
    zones: [
      { value: "America/New_York", label: "Eastern Time — New York" },
      { value: "America/Detroit", label: "Eastern Time — Detroit" },
      { value: "America/Indiana/Indianapolis", label: "Eastern Time — Indianapolis" },
      { value: "America/Chicago", label: "Central Time — Chicago" },
      { value: "America/Winnipeg", label: "Central Time — Winnipeg" },
      { value: "America/Denver", label: "Mountain Time — Denver" },
      { value: "America/Phoenix", label: "Mountain Time — Phoenix (no DST)" },
      { value: "America/Edmonton", label: "Mountain Time — Edmonton" },
      { value: "America/Los_Angeles", label: "Pacific Time — Los Angeles" },
      { value: "America/Vancouver", label: "Pacific Time — Vancouver" },
      { value: "America/Anchorage", label: "Alaska Time — Anchorage" },
      { value: "America/Honolulu", label: "Hawaii Time — Honolulu" },
      { value: "America/Toronto", label: "Eastern Time — Toronto" },
      { value: "America/Halifax", label: "Atlantic Time — Halifax" },
      { value: "America/St_Johns", label: "Newfoundland Time — St. John's" },
      { value: "America/Mexico_City", label: "Central Time — Mexico City" },
      { value: "America/Bogota", label: "Colombia Time — Bogotá" },
      { value: "America/Lima", label: "Peru Time — Lima" },
      { value: "America/Caracas", label: "Venezuela Time — Caracas" },
      { value: "America/Santiago", label: "Chile Time — Santiago" },
      { value: "America/Sao_Paulo", label: "Brasília Time — São Paulo" },
      { value: "America/Argentina/Buenos_Aires", label: "Argentina Time — Buenos Aires" },
    ],
  },
  {
    label: "Europe",
    zones: [
      { value: "Europe/London", label: "GMT/BST — London" },
      { value: "Europe/Dublin", label: "GMT/IST — Dublin" },
      { value: "Europe/Lisbon", label: "WET/WEST — Lisbon" },
      { value: "Europe/Paris", label: "CET/CEST — Paris" },
      { value: "Europe/Berlin", label: "CET/CEST — Berlin" },
      { value: "Europe/Amsterdam", label: "CET/CEST — Amsterdam" },
      { value: "Europe/Brussels", label: "CET/CEST — Brussels" },
      { value: "Europe/Madrid", label: "CET/CEST — Madrid" },
      { value: "Europe/Rome", label: "CET/CEST — Rome" },
      { value: "Europe/Zurich", label: "CET/CEST — Zurich" },
      { value: "Europe/Vienna", label: "CET/CEST — Vienna" },
      { value: "Europe/Stockholm", label: "CET/CEST — Stockholm" },
      { value: "Europe/Warsaw", label: "CET/CEST — Warsaw" },
      { value: "Europe/Prague", label: "CET/CEST — Prague" },
      { value: "Europe/Athens", label: "EET/EEST — Athens" },
      { value: "Europe/Bucharest", label: "EET/EEST — Bucharest" },
      { value: "Europe/Helsinki", label: "EET/EEST — Helsinki" },
      { value: "Europe/Kiev", label: "EET/EEST — Kyiv" },
      { value: "Europe/Istanbul", label: "TRT — Istanbul" },
      { value: "Europe/Moscow", label: "MSK — Moscow" },
    ],
  },
  {
    label: "Africa",
    zones: [
      { value: "Africa/Abidjan", label: "GMT — Abidjan" },
      { value: "Africa/Lagos", label: "WAT — Lagos" },
      { value: "Africa/Cairo", label: "EET — Cairo" },
      { value: "Africa/Nairobi", label: "EAT — Nairobi" },
      { value: "Africa/Johannesburg", label: "SAST — Johannesburg" },
    ],
  },
  {
    label: "Asia",
    zones: [
      { value: "Asia/Dubai", label: "GST — Dubai" },
      { value: "Asia/Karachi", label: "PKT — Karachi" },
      { value: "Asia/Kolkata", label: "IST — Kolkata / Mumbai" },
      { value: "Asia/Dhaka", label: "BST — Dhaka" },
      { value: "Asia/Bangkok", label: "ICT — Bangkok" },
      { value: "Asia/Jakarta", label: "WIB — Jakarta" },
      { value: "Asia/Singapore", label: "SGT — Singapore" },
      { value: "Asia/Kuala_Lumpur", label: "MYT — Kuala Lumpur" },
      { value: "Asia/Hong_Kong", label: "HKT — Hong Kong" },
      { value: "Asia/Shanghai", label: "CST — Shanghai / Beijing" },
      { value: "Asia/Taipei", label: "CST — Taipei" },
      { value: "Asia/Seoul", label: "KST — Seoul" },
      { value: "Asia/Tokyo", label: "JST — Tokyo" },
      { value: "Asia/Riyadh", label: "AST — Riyadh" },
      { value: "Asia/Tehran", label: "IRST — Tehran" },
      { value: "Asia/Kathmandu", label: "NPT — Kathmandu" },
      { value: "Asia/Colombo", label: "IST — Colombo" },
      { value: "Asia/Almaty", label: "ALMT — Almaty" },
    ],
  },
  {
    label: "Pacific & Australia",
    zones: [
      { value: "Australia/Perth", label: "AWST — Perth" },
      { value: "Australia/Darwin", label: "ACST — Darwin" },
      { value: "Australia/Adelaide", label: "ACST/ACDT — Adelaide" },
      { value: "Australia/Brisbane", label: "AEST — Brisbane" },
      { value: "Australia/Sydney", label: "AEST/AEDT — Sydney" },
      { value: "Australia/Melbourne", label: "AEST/AEDT — Melbourne" },
      { value: "Pacific/Auckland", label: "NZST/NZDT — Auckland" },
      { value: "Pacific/Fiji", label: "FJT — Fiji" },
      { value: "Pacific/Honolulu", label: "HST — Honolulu" },
      { value: "Pacific/Guam", label: "ChST — Guam" },
    ],
  },
];
